name: gtbuddy
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.5

  cupertino_icons: ^0.1.2
  json_model:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  google_maps_flutter: ^0.5.21+8
  shared_preferences: ^0.5.4+5
  permission_handler: ^3.0.1
  http: ^0.12.0+4
  flutter_bloc: ^2.0.0
  meta: ^1.1.6
  equatable: ^0.6.0
  bloc_pattern: ^2.3.2
  rflutter_alert: ^1.0.2
  font_awesome_flutter: ^8.5.0
  geolocator: ^5.1.5
  geocoder: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/routes_refactored/
    - assets/icons/splash_screen/BusIcon.png
    - assets/locations/BusStations.json
    - assets/routes_refactored/coords_Centurion.json
    - assets/routes_refactored/coords_Park.json
    - assets/routes_refactored/coords_Hatfield.json
    - assets/routes_refactored/coords_Midrand.json
    - assets/routes_refactored/coords_Pretoria.json
    - assets/routes_refactored/coords_Rhodesfield.json
    - assets/routes_refactored/coords_Rosebank.json
    - assets/routes_refactored/coords_Sandton.json
    - assets/routes_strings/
    - assets/routes_strings/coords_Centurion.json
    - assets/routes_strings/coords_Park.json
    - assets/routes_strings/coords_Hatfield.json
    - assets/routes_strings/coords_Midrand.json
    - assets/routes_strings/coords_Pretoria.json
    - assets/routes_strings/coords_Rhodesfield.json
    - assets/routes_strings/coords_Rosebank.json
    - assets/routes_strings/coords_Sandton.json
    - assets/bus_stops/AllBusStops.json
    - assets/bus_stops/stops_Pretoria.json
    - assets/bus_stops/stops_Park.json
    - assets/bus_stops/stops_Midrand.json
    - assets/bus_stops/stops_Sandton.json
    - assets/bus_stops/stops_Rosebank.json
    - assets/bus_stops/stops_Pretoria.json
    - assets/bus_stops/stops_Hatfield.json
    - assets/bus_stops/stops_Rhodesfield.json
    - assets/bus_stops/stops_Centurion.json
    - assets/bus_stops/stops_All.json
    - assets/icons/bus_stop/bus_stop@2x.png
    - assets/icons/live_bus/bus_position@2x.png

  fonts:
  - family: BeVietnam
    fonts:
      - asset: fonts/RedHatDisplay-Regular.ttf
